version: '3.8'
services:
  clustering:
    build: ./backend/clustering
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - clustering